name: Deploy NestJS App

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS
        run: npm run build

      - name: Debug file structure
        run: ls -R

      - name: Copy dist folder to server
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
          DEPLOY_KEY: ${{ secrets.SSH_PRIVATE_KEY }} # Your private SSH key
          run: |
            mkdir -p ~/.ssh
            echo "$DEPLOY_KEY" > ~/.ssh/id_rsa
            chmod 600 ~/.ssh/id_rsa
            ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "mkdir -p /home/backend/hrms"
            scp -r dist/* $DEPLOY_USER@$DEPLOY_HOST:/home/backend/hrms
            ssh -o StrictHostKeyChecking=no $DEPLOY_USER@$DEPLOY_HOST "pm2 restart 5 || pm2 restart hrms-be"