name: Deploy Next.js App to DigitalOcean Droplet

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      # Install and build locally on GitHub Actions
      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      # Upload only the build output + package files
      - name: Copy build to server via SSH
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: |
            dist
            package.json
            package-lock.json
          target: "/home/backend/hrms"
          strip_components: 0

      # SSH into server and restart PM2
      - name: SSH into server and deploy
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DEPLOY_HOST }}
          username: ${{ secrets.DEPLOY_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd /home/backend/hrms

            # Install dependencies only if package.json changed
            if [ "$(git diff --name-only HEAD~1 HEAD | grep package.json)" != "" ]; then
              echo "package.json changed - installing dependencies..."
              npm install --production
            else
              echo "package.json unchanged - skipping npm install."
            fi

            # Restart PM2 without deleting process
            if pm2 list | grep -q "hrms-be"; then
              pm2 restart hrms-be
            else
              pm2 start npm --name hrms-be -- run start
            fi

            pm2 save
