name: Deploy NestJS Backend to DigitalOcean 

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Set up SSH key
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy to server and build
        env:
          DEPLOY_HOST: ${{ secrets.DEPLOY_HOST }}
          DEPLOY_USER: ${{ secrets.DEPLOY_USER }}
        run: |
          APP_DIR="/home/backend/hrms"

          echo "Ensuring app directory exists..."
          ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" "mkdir -p $APP_DIR"

          echo "Syncing files to server..."
          rsync -avz --delete \
            --exclude='.git' \
            --exclude='node_modules' \
            -e "ssh -o StrictHostKeyChecking=no" \
            ./ "$DEPLOY_USER@$DEPLOY_HOST:$APP_DIR/"

          echo "Installing and building on server..."
          ssh -o StrictHostKeyChecking=no "$DEPLOY_USER@$DEPLOY_HOST" << 'EOF'
            cd /home/backend/hrms
            npm install --production
            npm install --save-dev @nestjs/cli
            npm run build

            if pm2 list | grep -q "hrms-be"; then
              pm2 restart hrms-be
            else
              pm2 start npm --name "hrms-be" -- run start
            fi

            pm2 save
          EOF
